//#Include "Rwmake.ch"
//#Include "Topconn.ch" 
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑบPrograma  ณAT310ROT  บAutor  ณEduardo B. MantoanบData ณ 15/12/14       บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ  Menu TECA310  										      บฑฑ
ฑฑบ          ณ  											              บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP - MASIPACK.                                             บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/


User Function AT310ROT ( ) 
 
Local aRet := { }  

aAdd(aRet,{'Envia e-mail p/ t้cnico','u_RTECG005', 0 , 2})  
//aAdd(aRet,{'Help-Desk'			    ,'u_RTECG006', 0 , 2}) 

/*aRotina := {	{STR0002	,"AxPesqui"  	,0	,1	,0	,.F.	}	,;    //"Pesquisar"
						{STR0003	,"AT310Visua"	,0	,2	,0	,.T. 	}	,;    //"Visualizar"
						{STR0004	,"AT310Inclu"	,0	,3	,0	,.T.	}	,;    //"Incluir"
						{STR0005	,"AT310Alter"	,0	,4	,0	,.T.	}	,;    //"Alterar"
						{STR0006	,"AT310Exclu"	,0	,5	,0	,.T.	}	,;    //"Exclui"
						{STR0038	,"AT310Listen"	,0	,3	,0	,.T.	}	}   //"Listener"    */



Return aRet