#IFDEF SPANISH
   #define STR0001 "CAD. METAS DE COMISIONES"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "CAD. METAS DE COMISSOES"
   #ELSE
      #define STR0001 "CAD. METAS DE COMISSOES"
   #ENDIF
#ENDIF
