#ifdef SPANISH
		#DEFINE STR0001 "No hay ninguna tabla seleccionada"
		#DEFINE STR0002 "Las listas de precios"		
		#DEFINE STR0003 "Aguarde, abrindo tabela de preços"
#else
	#ifdef ENGLISH
		#DEFINE STR0001 "There is no table selected"
		#DEFINE STR0002 "Price lists"	
		#DEFINE STR0003 "Aguarde, abrindo tabela de preços"
	#else
		#DEFINE STR0001 "Não existe tabela selecionada"
		#DEFINE STR0002 "Tabela de preços"	
		#DEFINE STR0003 "Aguarde, abrindo tabela de preços"
	#endif
#endif